packages:
  - app/
  - packages/*
  - tooling/*

catalog:
  "@trpc/client": "^11.4.3"
  "@trpc/server": "^11.4.3"
  "@tanstack/react-start": "^1.132.27"
  "@lucia-auth/adapter-drizzle": "^1.1.0"
  lucia: ^3.2.2
  typescript: ^5.8.3
  zod: ^4.0.0
  eslint: ^9.28.0
  prettier: ^3.5.3
