export const genreValues = [
  "action",
  "aventure",
  "comédie",
  "drame",
  "fantastique",
  "horreur",
  "mystère",
  "psychologique",
  "romance",
  "science-fiction",
  "slice of life",
  "sport",
  "surnaturel",
  "thriller",
  "historique",
  "arts martiaux",
  "militaire",
  "mecha",
  "musique",
  "policier",
  "ecchi",
  "yaoi",
  "yuri",
  "isekai",
  "tranche de vie",
  "cyberpunk",
  "space opera",
  "voyage temporel",
  "cuisine",
  "animaux",
] as const;

export type GenreValues = typeof genreValues;
export type Genre = GenreValues[number];

export const genre = {
  ACTION: "action",
  AVENTURE: "aventure",
  COMEDIE: "comédie",
  DRAME: "drame",
  FANTASTIQUE: "fantastique",
  HORREUR: "horreur",
  MYSTERE: "mystère",
  PSYCHOLOGIQUE: "psychologique",
  ROMANCE: "romance",
  SCIENCE_FICTION: "science-fiction",
  SLICE_OF_LIFE: "slice of life",
  SPORT: "sport",
  SURNATUREL: "surnaturel",
  THRILLER: "thriller",
  HISTORIQUE: "historique",
  ARTS_MARTIAUX: "arts martiaux",
  MILITAIRE: "militaire",
  MECHA: "mecha",
  MUSIQUE: "musique",
  POLICIER: "policier",
  ECCHI: "ecchi",
  YAOI: "yaoi",
  YURI: "yuri",
  ISEKAI: "isekai",
  TRANCHE_DE_VIE: "tranche de vie",
  CYBERPUNK: "cyberpunk",
  SPACE_OPERA: "space opera",
  VOYAGE_TEMPOREL: "voyage temporel",
  CUISINE: "cuisine",
  ANIMAUX: "animaux",
} as const satisfies Record<string, Genre>;

export const genreLabelFrench = {
  [genre.ACTION]: "Action",
  [genre.AVENTURE]: "Aventure",
  [genre.COMEDIE]: "Comédie",
  [genre.DRAME]: "Drame",
  [genre.FANTASTIQUE]: "Fantastique",
  [genre.HORREUR]: "Horreur",
  [genre.MYSTERE]: "Mystère",
  [genre.PSYCHOLOGIQUE]: "Psychologique",
  [genre.ROMANCE]: "Romance",
  [genre.SCIENCE_FICTION]: "Science-fiction",
  [genre.SLICE_OF_LIFE]: "Slice of Life",
  [genre.SPORT]: "Sport",
  [genre.SURNATUREL]: "Surnaturel",
  [genre.THRILLER]: "Thriller",
  [genre.HISTORIQUE]: "Historique",
  [genre.ARTS_MARTIAUX]: "Arts martiaux",
  [genre.MILITAIRE]: "Militaire",
  [genre.MECHA]: "Mecha",
  [genre.MUSIQUE]: "Musique",
  [genre.POLICIER]: "Policier",
  [genre.ECCHI]: "Ecchi",
  [genre.YAOI]: "Yaoi",
  [genre.YURI]: "Yuri",
  [genre.ISEKAI]: "Isekai",
  [genre.TRANCHE_DE_VIE]: "Tranche de vie",
  [genre.CYBERPUNK]: "Cyberpunk",
  [genre.SPACE_OPERA]: "Space opera",
  [genre.VOYAGE_TEMPOREL]: "Voyage temporel",
  [genre.CUISINE]: "Cuisine",
  [genre.ANIMAUX]: "Animaux",
} as const satisfies Record<Genre, string>;
